### ISSUE TITLE
Unable to automatically install 'XML2' from 'XML2_jll/XWlin/Artifacts.toml'

### ISSUE THREAD

**Issue by singularitti** [JuliaBinaryWrappers/XML2_jll.jl#1] opened 2020-06-19 12:46 UTC
I am having trouble installing a package that has this as a dependency when installing it on a remote server, it says

```julia
(@v1.4) pkg> add XML2_jll
  Resolving package versions...
ERROR: Unable to automatically install 'XML2' from '~/.julia/packages/XML2_jll/XWlin/Artifacts.toml'
Stacktrace:
 [1] error(s::String)
   @ Base ~/julia/bin/../share/julia/base/error.jl:33

 [2] #ensure_artifact_installed#42(platform::Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, ::typeof(Pkg.Artifacts.ensure_artifact_installed), name::String, meta::Dict{String,Any}, artifacts_toml::String)
   @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Artifacts.jl:894

 [3] #ensure_all_artifacts_installed#47(platform::Pkg.BinaryPlatforms.Platform, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool, ::typeof(Pkg.Artifacts.ensure_all_artifacts_installed), artifacts_toml::String)
   @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Artifacts.jl:958

 [4] #download_artifacts#41(platform::Pkg.BinaryPlatforms.Linux, verbose::Bool, ::typeof(Pkg.Operations.download_artifacts), ctx::Pkg.Types.Context, pkg_roots::Array{String,1})
   @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:616

 [5] #download_artifacts#38(platform::Pkg.BinaryPlatforms.Linux, verbose::Bool, ::typeof(Pkg.Operations.download_artifacts), ctx::Pkg.Types.Context, pkgs::Array{Pkg.Types.PackageSpec,1})
   @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:595

 [6] #add#75(preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux, ::typeof(Pkg.Operations.add), ctx::Pkg.Types.Context, pkgs::Array{Pkg.Types.PackageSpec,1}, new_git::Array{Base.UUID,1})
   @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:1091

 [7] #add#28(preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.add), ctx::Pkg.Types.Context, pkgs::Array{Pkg.Types.PackageSpec,1})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:159

 [8] add(ctx::Pkg.Types.Context, pkgs::Array{Pkg.Types.PackageSpec,1})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:112

 [9] #add#27
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:109 [inlined]

[10] add(pkgs::Array{Pkg.Types.PackageSpec,1})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:109

[11] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
   @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/REPLMode/REPLMode.jl:402

[12] #do_cmd#21(do_rethrow::Bool, ::typeof(Pkg.REPLMode.do_cmd), repl::REPL.LineEditREPL, input::String)
   @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/REPLMode/REPLMode.jl:380

[13] do_cmd
   @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/REPLMode/REPLMode.jl:375 [inlined]

[14] #24(s::REPL.LineEdit.MIState, buf::Base.GenericIOBuffer{Array{UInt8,1}}, ok::Bool)
   @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/REPLMode/REPLMode.jl:541

[15] #invokelatest#1
   @ ~/julia/bin/../share/julia/base/essentials.jl:712 [inlined]

[16] invokelatest
   @ ~/julia/bin/../share/julia/base/essentials.jl:711 [inlined]

[17] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
   @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2354

[18] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
   @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055

[19] run_repl(repl::REPL.AbstractREPL, consumer::Any)
   @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206

[20] #764(REPL::Module)
   @ Base ~/julia/bin/../share/julia/base/client.jl:383

[21] #invokelatest#1
   @ ~/julia/bin/../share/julia/base/essentials.jl:712 [inlined]

[22] invokelatest
   @ ~/julia/bin/../share/julia/base/essentials.jl:711 [inlined]

[23] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
   @ Base ~/julia/bin/../share/julia/base/client.jl:367

[24] exec_options(opts::Base.JLOptions)
   @ Base ~/julia/bin/../share/julia/base/client.jl:305

[25] _start
   @ Base ~/julia/bin/../share/julia/base/client.jl:484
```

```julia
a Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon Phi(TM) CPU 7250 @ 1.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, knl)
Environment:
  JULIA_PKG_SERVER = https://us-east.pkg.julialang.org/
  JULIA_EDITOR = vim
```

**Comment by giordano** [comment] 2020-06-19 13:04
Use https://github.com/giordano/DebugArtifacts.jl to find what's the problem.  Anyway, nothing we can do here

**Comment by singularitti** [comment] 2020-06-20 06:05
I think the reason is that
```julia
failed process: Process(`curl -C - '-#' -f -o /tmp/jl_uRo7JY/Artifacts.toml -L https://raw.githubusercontent.com/JuliaBinaryWrappers/XML2_jll.jl/master/Artifacts.toml`, ProcessSignaled(4)) [0]
```
I do not have write permission to `/tmp/`, which requires root permission. Is there a setting that I can change the directory of downloaded artifacts?

**Comment by giordano** [comment] 2020-06-20 10:23
No idea, the download is done on the Pkg side. Try asking on discourse, or open an issue for Pkg if you believe there is no option to change the download directory.

I'm going to close this ticket now that you've confirmed the issue is unrelated to this package.

**Closed by giordano** 2020-06-20 10:23 UTC

**Comment by giordano** [comment] 2020-06-20 10:25
Actually, DebugArtifacts.jl might be lying to you in this case because it downloads the Artifacts.toml into the temporary directory, something that Pkg doesn't do. I'll need to check something

**Comment by giordano** [comment] 2020-06-20 10:29
Ok, the actual download might not go through the temporary directory.

Anyway the download is done by Pkg, so if the download is failing, there is something going wrong on that side.

**Comment by singularitti** [comment] 2020-06-20 11:40
Thanks!
